version: "3.9"
services:
  db:
    image: postgres:14.3-alpine
    container_name: news-portal-api-db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    restart: always
  app:
    build: .
    container_name: news-portal-api-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3100 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - gems:/usr/local/bundle:cached
    ports:
      - "3100:3100"
    depends_on:
      - db
    restart: on-failure
volumes:
  db:
  gems: