default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_development

test:
  <<: *default
  database: news_test

production:
  <<: *default
  database: news_production
  username: news_portal_api
  password: <%= ENV["NEWS_PORTAL_API_DATABASE_PASSWORD"] %>
